service: decoo
app: decoo
org: decoo

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: test      # Always keep it as test, and to deploy to prod/dev stage just merge your code to dev/master branch on Github
  region: us-west-1
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchPutItem
          - dynamodb:BatchWriteItem
        Resource: "*"
  environment:
    GOOGLE_API_KEY: ${param:google_api_key}
    BEST_TIMES_API_KEY: ${param:best_times_api_key}

functions:
  nearbyPlaces:
    handler: places.nearby
    events:
    - httpApi:
        path: /places/nearby
        method: post
    timeout: 20
  allPlaces:
    handler: places.all
    events:
    - httpApi:
        path: /places/all
        method: get
    timeout: 20

  # These are cron jobs 
  # updater:
  #   handler: places.updater # Monitoring of all live centers
  #   events:
  #     - schedule: rate(30 minutes)
  #   timeout: 600


resources:
  Resources:
    placeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: places-${opt:stage, 'test'}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: geohash
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: geohash
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    geohashesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: geohashes-${opt:stage, 'test'}
        AttributeDefinitions:
          - AttributeName: geohash
            AttributeType: S
        KeySchema:
          - AttributeName: geohash
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
