service: decoo
app: decoo
org: decoo

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource: "*"

functions:
  nearbyPlaces:
    handler: places.nearby
    events:
    - httpApi:
        path: /places/nearby
        method: post

resources:
  Resources:
    placesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: places
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: geohash
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: geohash
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
